//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashp.AuthenticationService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationState
    {
        public AuthenticationState()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int AuthenticationStateCode { get; set; }
        public string AuthenticationState1 { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
    }
}
