//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashp.AuthenticationService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid LogUID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string IPAddress { get; set; }
        public string Referer { get; set; }
        public string AuthorizationRequestHeader { get; set; }
        public string AuthorizationQueryString { get; set; }
        public string DecodedAuthorizationString { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AppCode { get; set; }
        public bool AshpLoginAttempted { get; set; }
        public Nullable<bool> ServerOK { get; set; }
        public Nullable<bool> LoginOK { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int AuthenticationState { get; set; }
    
        public virtual AuthenticationState AuthenticationState1 { get; set; }
    }
}
